export const MAIN_HREF = {
  AUTH: '/auth',
  HOME: '/home',
  LANDING: '/',
};

export const ROUTES = {
  SHARED: {
    AUTH: '/auth',
    HOME: '/home',
    LANDING: '/',
  },
  BACKOFFICE: {
    HOME: '/',
    AUTH: '/auth',
    DASHBOARD: '/dashboard',
    APPLICANT_HISTORY: '/applicant-history',
    CLIENT_CREATION: '/client-creation',
    CLIENT_DETAILS: '/client-details',
    CLIENT_HISTORY: '/client-history',
    CLIENT_LIST: '/client-list',
    EDIT_CLIENT_INFO: '/edit-client-info',
    EDIT_APPLICANT_INFO: '/edit-applicant-info',
    EDIT_SERVICE: '/edit-service',
    EDIT_SCOPE: '/edit-scope',
    SCOPE_CREATION: '/scope-creation',
    SCOPE_LIST: '/scope-list',
    SERVICE_HISTORY: '/service-history',
    SERVICE_DETAILS: '/service-details',
    SERVICE_LIST: '/service-list',
    UPSTREAM_CREATION: '/upstream-creation',
    UPSTREAM_DETAILS: '/upstream-details',
    UPSTREAM_LIST: '/upstream-list',
    SERVICE_CREATION: '/service-creation',
    SCOPE_HISTORY: '/scope-history',
    SCOPE_INFORMATION: '/scope-information',
    EDIT_ROUTE: '/edit-route',
    ROUTE_HISTORY: '/route-history',
  },
  CUSTOMER: {
    LANDING: '/',
    AUTH: '/auth',
    DASHBOARD: '/dashboard',
    REQUEST_MANAGEMENT: '/request-management',
    REQUEST_REGISTRATION: '/request-registration',
    REQUEST_DETAILS_INFO: '/request-details-info',
  },
  BUSINESS: {
    AUTH: '/auth',
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    REQUESTS_MANAGEMENT: '/requests-management',
    REQUEST_LIST: '/request-list',
    REQUEST_DETAILS: '/request-details',
    EDIT_REQUEST_LIST: '/edit-request-list',
  },
};
export const CUSTOMER_ROUTE_GROUPS = [
  // [ROUTES.CUSTOMER.DASHBOARD],
  [ROUTES.CUSTOMER.REQUEST_MANAGEMENT, ROUTES.CUSTOMER.REQUEST_REGISTRATION],
];

export const BACKOFFICE_ROUTE_GROUPS = [
  // ['/dashboard', '/dashboard-report'],
  [
    ROUTES.BACKOFFICE.APPLICANT_HISTORY,
    ROUTES.BACKOFFICE.CLIENT_CREATION,
    ROUTES.BACKOFFICE.CLIENT_DETAILS,
    ROUTES.BACKOFFICE.CLIENT_HISTORY,
    ROUTES.BACKOFFICE.CLIENT_LIST,
    ROUTES.BACKOFFICE.EDIT_CLIENT_INFO,
    ROUTES.BACKOFFICE.EDIT_APPLICANT_INFO,
  ],
  [
    ROUTES.BACKOFFICE.EDIT_SERVICE,
    ROUTES.BACKOFFICE.SERVICE_HISTORY,
    ROUTES.BACKOFFICE.SERVICE_LIST,
    ROUTES.BACKOFFICE.SERVICE_DETAILS,
    ROUTES.BACKOFFICE.SERVICE_CREATION,
  ],
  [
    ROUTES.BACKOFFICE.EDIT_SCOPE,
    ROUTES.BACKOFFICE.SCOPE_CREATION,
    ROUTES.BACKOFFICE.SCOPE_LIST,
    ROUTES.BACKOFFICE.SCOPE_INFORMATION,
  ],
  [ROUTES.BACKOFFICE.EDIT_ROUTE, ROUTES.BACKOFFICE.ROUTE_HISTORY],
  [ROUTES.BACKOFFICE.UPSTREAM_LIST, ROUTES.BACKOFFICE.UPSTREAM_CREATION],
  [ROUTES.BUSINESS.REQUEST_LIST, ROUTES.BUSINESS.REQUEST_DETAILS],
];
