export { ReactComponent as BaamsunLogo } from './baamsun-logo.svg';
export { ReactComponent as BankLogo } from './bank-logo.svg';
export { ReactComponent as OxygenLogo } from './oxygen-logo-light-mode.svg';
export { ReactComponent as OxygenDarkLogo } from './oxygen-logo-dark-mode.svg';
export { ReactComponent as BaamsunLogoPrimary } from './baamsun-logo-primary.svg';
export { ReactComponent as BankLogoRed } from './bank_logo_red.svg';
export { ReactComponent as PencilSquare } from './pencil-square.svg';
export { ReactComponent as UserProfile } from './user-profile.svg';
export { ReactComponent as SignOut } from './sign-out.svg';
export { ReactComponent as Sort } from './sort.svg';
export { ReactComponent as InputPassword } from './Input-password.svg';
export { ReactComponent as ArrowDown } from './arrow-down.svg';
export { ReactComponent as EmptyIcon } from './empty-state.svg';
export { ReactComponent as ActiveBadge } from './active-badge.svg';
export { ReactComponent as InactiveBadge } from './inactive-badge.svg';
export { ReactComponent as SadadLogoLight } from './sadad-logo-light.svg';

// export {ReactComponent as AuthBG} from './media/auth-bg.svg';
export * as bankLogo from './bank.png';
export * as bankLogoBlack from './bank_logo_black.png';
