import { BaseProvider } from '../providers';
import { iransans } from './fonts';
// import '../../public/assets/fonts/font.css';

export const metadata = {
  title: 'Welcome to portal',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${iransans.variable}`}>
    <body>
    <BaseProvider>
      {children}
    </BaseProvider>
    </body>
    </html>
  );
}
