import { BaseProvider } from '@oxygen/hooks';

import { StyledComponentsRegistry } from './registry';
import 'normalize.css';
import { iransans } from './fonts';

export const metadata = {
  title: 'Welcome to portal',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={`${iransans.variable}`}>
      <body>
        <StyledComponentsRegistry>
          <BaseProvider>{children}</BaseProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
