export const FORM_ITEM_NAMES = {
  latin_name_client: 'latin_name_client',
  grant_type: 'grant_type',
  tags: 'tags',
  persian_name_client: 'persian_name_client',
  client_type: 'client_type',
  client_id: 'client_id',
  identity_auth: 'identity_auth',
  website_url: 'website_url',
  input_address: 'input_address',
  return_address: 'return_address',
  aggregator_status: 'aggregator_status',
  aggregator: 'aggregator',
  user_name: 'user_name',
  national_code: 'national_code',
  organization_name: 'organization_name',
  mobile_number: 'mobile_number',
  telephone: 'telephone',
  email: 'email',
};
