export const FORM_ITEM_NAMES = {
  latinNameClient: 'latinNameClient',
  grantType: 'grantType',
  tags: 'tags',
  persianNameClient: 'persianNameClient',
  clientType: 'clientType',
  clientId: 'clientId',
  identityAuth: 'identityAuth',
  websiteUrl: 'websiteUrl',
  inputAddress: 'inputAddress',
  returnAddress: 'returnAddress',
  aggregatorStatus: 'aggregatorStatus',
  aggregator: 'aggregator',
  userName: 'userName',
  nationalCode: 'nationalCode',
  organizationName: 'organizationName',
  mobileNumber: 'mobileNumber',
  telePhone: 'telePhone',
  email: 'email',
};
