export { ReactComponent as BaamsunLogo } from './media/baamsun-logo.svg';
export { ReactComponent as BankLogo } from './media/bank-logo.svg';
export { ReactComponent as OxygenLogo } from './media/oxygen-logo-light-mode.svg';
export { ReactComponent as OxygenDarkLogo } from './media/oxygen-logo-dark-mode.svg';
export { ReactComponent as BaamsunLogoPrimary } from './media/baamsun-logo-primary.svg';
export { ReactComponent as BankLogoRed } from './media/bank_logo_red.svg';
export { ReactComponent as PencilSquare } from './media/pencil-square.svg';
export { ReactComponent as UserProfile } from './media/user-profile.svg';
export { ReactComponent as SignOut } from './media/sign-out.svg';
export { ReactComponent as Sort } from './media/sort.svg';
export { ReactComponent as InputPassword } from './media/Input-password.svg';
export { ReactComponent as ArrowDown } from './media/arrow-down.svg';
export { ReactComponent as EmptyIcon } from './media/empty-state.svg';
export { ReactComponent as ActiveBadge } from './media/active-badge.svg';
export { ReactComponent as InactiveBadge } from './media/inactive-badge.svg';
export { ReactComponent as SadadLogoLight } from './media/sadad-logo-light.svg';
export { ReactComponent as Refresh } from './media/refresh.svg';

// export {ReactComponent as AuthBG} from './media/auth-bg.svg';
export * as bankLogo from './media/bank.png';
export * as bankLogoBlack from './media/bank_logo_black.png';
