import { getOrganizations } from 'libs/mockify/src/client-list.mock';

export const limits = {
  DEFAULT_MAX_LENGTH: 255,
  DEFAULT_MIN_LENGTH: 3,
  ORGANIZATION_NUMBER: 12,
  ORGANIZATION_NATIONAL_ID_NUMBER: 11,
  ORGANIZATION_ECONOMY_CODE_NUMBER: 12,
  PHONE_NUMBER: 12,
  TELL: 11,
  UPSTREAM_MAX_LENGTH: 150,
  POSTAL_CODE_NUMBER: 10,
  UPSTREAM_SERVICE_WEIGHT_MAX_NUMBER: 100,
  VERSION_MAX: 3,
};
